site_name: My Docs
nav:
  - 简介: index.md
  - C语言: 
    - 函数指针: c语言/函数指针.md
theme: 
    name: rtd-dropdown
    # Default settings
    collapse_by_default: false
    highlightjs: true
    hljs_languages:
        - yaml
        - django